# Generated by Django 4.1 on 2022-09-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_number',
            field=models.IntegerField(),
        ),
    ]
